// Mirrors the `tag` values in ai-crawling-pipeline/configs/radar_sources.yaml —
// the read API has no "list companies" endpoint (see read-api/README.md), so
// the filter's full universe of options is hand-maintained here, same
// duplication tradeoff as lib/types.ts. Update this list by hand when a tag is
// added or removed from radar_sources.yaml.
export const COMPANIES: string[] = [
  "Andap",
  "Anfavea",
  "Arteb",
  "Automec",
  "BCB",
  "BorgWarner",
  "Bosch",
  "Continental",
  "Câmbio",
  "Dayco",
  "Denso",
  "DPK",
  "Eaton",
  "Exedy",
  "Fenabrave",
  "Fortbras",
  "Fras-le",
  "Gates",
  "GPC",
  "Hella",
  "IA",
  "IBGE",
  "Laguna",
  "MAHLE",
  "MANN+HUMMEL",
  "Marelli",
  "Mercado",
  "Nakata",
  "NGK",
  "Osram",
  "Pellegrino",
  "Philips",
  "Randon",
  "Sabó",
  "Schaeffler",
  "Shocklight",
  "Sindipeças",
  "Sindirepa",
  "SK Automotive",
  "SKF",
  "Tecfil",
  "Tecnologia",
  "Tenneco",
  "Trico",
  "Valeo",
  "Wega",
  "ZF",
].sort((a, b) => a.localeCompare(b));
